# Generated by Django 4.2 on 2025-01-23 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    replaces = [
        ("users", "0001_initial"),
        (
            "users",
            "0002_rename_permissions_request_useraccessrequests_permissions_requested",
        ),
    ]

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True,
                        help_text="Email Address",
                        max_length=254,
                        unique=True,
                        verbose_name="email address",
                    ),
                ),
                (
                    "mobile_no",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Mobile No",
                        max_length=20,
                        null=True,
                        verbose_name="mobile no",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Name",
                        max_length=50,
                        verbose_name="name",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("Admin", "Admin"), ("Member", "Member")],
                        help_text="User Role",
                        max_length=10,
                        verbose_name="role",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False, help_text="Is Staff", verbose_name="is staff"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Is Superuser",
                        verbose_name="is superuser",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Is Active", verbose_name="is active"
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date Joined",
                        verbose_name="date joined",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
            },
        ),
        migrations.CreateModel(
            name="UserPermissions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "permissions",
                    models.JSONField(
                        default=dict,
                        help_text="Permissions granted to the user",
                        verbose_name="permissions",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Updated At", verbose_name="updated at"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Updated By",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_permissions",
                        related_query_name="updated_permissions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="updated by",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="User",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permissions",
                        related_query_name="permissions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "user permissions",
                "verbose_name_plural": "user permissions",
            },
        ),
        migrations.CreateModel(
            name="UserAccessTokens",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        help_text="Token",
                        max_length=255,
                        unique=True,
                        verbose_name="token",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("web", "Web"), ("api", "API")],
                        help_text="Type of token",
                        max_length=50,
                        verbose_name="type",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Created At",
                        verbose_name="created at",
                    ),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last Used At",
                        null=True,
                        verbose_name="last used at",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auth_tokens",
                        related_query_name="auth_tokens",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "user access token",
                "verbose_name_plural": "user access tokens",
            },
        ),
        migrations.CreateModel(
            name="UserAccessRequests",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "approved",
                    models.BooleanField(
                        default=False, help_text="Approved", verbose_name="approved"
                    ),
                ),
                (
                    "permissions_requested",
                    models.JSONField(
                        default=dict,
                        help_text="Requested Permissions",
                        verbose_name="permissions request",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Reason for request",
                        null=True,
                        verbose_name="description",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Created At",
                        verbose_name="created at",
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Approved At",
                        null=True,
                        verbose_name="approved at",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Approved By",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_requests",
                        related_query_name="approved_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="approved by",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_requests",
                        related_query_name="access_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "user access request",
                "verbose_name_plural": "user access requests",
            },
        ),
    ]
