# Generated by Django 4.2 on 2025-02-15 11:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "users",
            "0001_squashed_0002_rename_permissions_request_useraccessrequests_permissions_requested",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="useraccesstokens",
            name="token",
        ),
        migrations.AddField(
            model_name="useraccesstokens",
            name="auth_token",
            field=models.CharField(
                default="",
                help_text="Auth Token",
                max_length=255,
                unique=True,
                verbose_name="auth token",
            ),
        ),
    ]
