# Generated by Django 4.2 on 2025-02-15 11:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_remove_useraccesstokens_token_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraccesstokens",
            name="device_token",
            field=models.CharField(
                default="",
                help_text="Device Token",
                max_length=255,
                unique=True,
                verbose_name="device token",
            ),
        ),
    ]
