# Generated by Django 4.2 on 2025-01-23 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WeatherStations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the weather station",
                        max_length=255,
                        verbose_name="name",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        help_text="Location of the station (e.g., city, coordinates)",
                        max_length=255,
                        verbose_name="location",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of the station",
                        null=True,
                        verbose_name="description",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp of when the station was created",
                        verbose_name="created at",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created the station",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_stations",
                        related_query_name="created_stations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
            ],
            options={
                "verbose_name": "weather station",
                "verbose_name_plural": "weather stations",
            },
        ),
        migrations.CreateModel(
            name="StationAccessTokens",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        help_text="Token string for accessing the station data",
                        max_length=255,
                        unique=True,
                        verbose_name="token",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Label for the station access token",
                        max_length=255,
                        verbose_name="label",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of the station access token",
                        null=True,
                        verbose_name="description",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp of when the access token was created",
                        verbose_name="created at",
                    ),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of when the access token was last used",
                        null=True,
                        verbose_name="last used at",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created the access token",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_tokens",
                        related_query_name="created_token",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        help_text="Weather station to which the access token belongs",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_tokens",
                        related_query_name="access_token",
                        to="stations.weatherstations",
                        verbose_name="station",
                    ),
                ),
            ],
            options={
                "verbose_name": "station access token",
                "verbose_name_plural": "station access tokens",
            },
        ),
        migrations.CreateModel(
            name="Sensors",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the sensor",
                        max_length=255,
                        verbose_name="name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of the sensor",
                        null=True,
                        verbose_name="description",
                    ),
                ),
                (
                    "data_identifier",
                    models.CharField(
                        help_text="Identifier of the sensor in the station data",
                        max_length=255,
                        verbose_name="data identifier",
                    ),
                ),
                (
                    "units",
                    models.CharField(
                        help_text="Units of the data acquired by the sensor",
                        max_length=50,
                        verbose_name="units",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="If the sensor is currently active or not",
                        verbose_name="active",
                    ),
                ),
                (
                    "last_deactivated_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of when the sensor was deactivated",
                        null=True,
                        verbose_name="last deactivated at",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp of when the sensor was created",
                        verbose_name="created at",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created the sensor",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_sensors",
                        related_query_name="created_sensor",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        help_text="Weather station to which the sensor belongs",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sensors",
                        related_query_name="sensor",
                        to="stations.weatherstations",
                        verbose_name="station",
                    ),
                ),
            ],
            options={
                "verbose_name": "sensor",
                "verbose_name_plural": "sensors",
            },
        ),
        migrations.CreateModel(
            name="SensorData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Data recorded by the sensor",
                        max_digits=10,
                        verbose_name="data",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        help_text="Date and time when the data was recorded",
                        verbose_name="timestamp",
                    ),
                ),
                (
                    "sensor",
                    models.ForeignKey(
                        help_text="Sensor that recorded the data",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data",
                        related_query_name="datum",
                        to="stations.sensors",
                        verbose_name="sensor",
                    ),
                ),
            ],
            options={
                "verbose_name": "sensor data",
                "verbose_name_plural": "sensor data",
            },
        ),
    ]
